language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
install:
- dotnet restore
script:
- dotnet build
- dotnet test Hiring.Kloud.CodeChallenge.Test/Hiring.Kloud.CodeChallenge.Test.csproj
deploy:
  provider: azure_web_apps
notifications:
  email:
    - samuraitruong@hotmail.com